### PR TITLE
Removed setup_version from module.xml for zero downtime deploy.

### PR DESCRIPTION
**Pull request by davekleijn**
This change will allow zero downtime deployments.

### CODE REVIEW

**Comment by convenient** [comment]
This was a silly mistake on my part. Can you think of any problems with removing this for people who already have the module deployed?

**Comment by davekleijn** [comment]
Hi @convenient,

No problem at all. I am very happy with all the effort you have made.

The only thing I can think of is that `Gene_EncryptionKeyManager` is added to `setup_module` table in the database. But this should not be a problem. It is only for backwards compatibility.

If a setup script is added later in time (with version 0.1.0) the script is not running again. But still this is a old way of doing things. Data patches can be used.

**Comment by davekleijn** [comment]
Furthermore, I don't think that users with a very old Magento version use this module, because they first have to update their Magento before they can even install the latest patch of Magento.

**Comment by davekleijn** [comment]
Looks like Magento removed them in 2018 already. (https://github.com/magento/magento2/commit/7120e062be824549b8f7b07a611c15fbca64484f)

So as of Magento 2.3.0 it's not required anymore. Therefore this module is not backwards compatible before Magento 2.3.0 when adding this PR.

**Comment by convenient** [comment]
Thanks @davekleijn , I'll merge and tag when I'm at a computer soon

**Pull request merged**
